/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    PokemonCard: typeof import('./src/components/PokemonCard.vue')['default']
    PokemonSearch: typeof import('./src/components/PokemonSearch.vue')['default']
    PokemonStats: typeof import('./src/components/PokemonStats.vue')['default']
    PokemonTypesChips: typeof import('./src/components/PokemonTypesChips.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectImageTest: typeof import('./src/components/SelectImageTest.vue')['default']
    SelectImageTestPokemon: typeof import('./src/components/SelectImageTestPokemon.vue')['default']
    TypeChip: typeof import('@/components/TypeChips.vue')['default']
    TypeChips: typeof import('@/components/PokemonTypesChips.vue')['default']
  }
}
